{{ config(materialized='table') }}
with LI AS
(
select 
L_ORDERKEY, L_LINENUMBER, L_QUANTITY, L_DISCOUNT, L_TAX, L_LINESTATUS, L_SHIPDATE, L_COMMITDATE, L_RECEIPTDATE
from DB_DEV.RAW.LINEITEM
)
SELECT * FROM LI