
WITH ORD AS
(
select *
from {{ ref('ORDERS') }}
),

CUST AS
(
select *
from {{ ref('cust') }}
),

LI AS
(
select *
from {{ ref('LINEITEM') }}
)

SELECT O.O_ORDERKEY, O.O_CUSTKEY, O.O_ORDERSTATUS, O.O_TOTALPRICE, O.O_ORDERDATE, O.O_ORDERPRIORITY,
C.C_NAME, C.C_ADDRESS, C.C_NATIONKEY, C.C_PHONE, C.C_ACCTBAL,
L.L_LINENUMBER, L.L_QUANTITY, L.L_DISCOUNT, L.L_TAX, L.L_LINESTATUS, L.L_SHIPDATE, L.L_COMMITDATE, 
L.L_RECEIPTDATE
FROM ORD O
LEFT JOIN CUST C
ON O.O_CUSTKEY = C.C_CUSTKEY
LEFT JOIN LI L
ON O.O_ORDERKEY = L.L_ORDERKEY
